# Project Euler 29
# How many distinct terms are in the sequence generated by a^b for
# 2 <= a <= 100 and 2 <= b <= 100

distinct = set()

for a in range(2,101):
    for b in range(2,101):
        cur = a**b
        if cur not in distinct:
            distinct.add(cur)

print(len(distinct))
